GET http://localhost:3000/api/libros/
Content-Type: application/json
Accept: application/json

{
  "titulo": "El Tunel",
  "autor": "Ernesto Sabato",
  "stock": 1,
  "editorial": "Editorial Sudamericana",
  "precio": 5900,
  "isbn": "9789878000114",
  "generos": ["Ficción", "Suspenso"]
}
